### PR TITLE
feat: use sonner as toast

### PR DESCRIPTION
**Pull request by chef-jojo**
Improve toast and stack

It doesn't need hook, useToast anymore. for now just leave it as how we use it

https://github.com/pancakeswap/pancake-frontend/assets/94336009/7731d0ae-e4a2-4f19-b747-8ff66f214405

---

### Detailed summary
- The `ToastContainer` component has been deleted.
- The `Toast` component has been updated with new props and styling.
- The `ToastsContext` has been modified to use the `sonner` library for displaying toasts.
- The `ToastListener` component has been updated to use the new `Toaster` component from `sonner`.
- The `ToastData` interface has been updated to include an optional `description` field and the `id` field can now be either a string or a number.
- The `ToastProps` interface has been updated to use the new `onRemove` prop.
- The `Toast.stories.tsx` file has been added with a new story for the `Toast` component.
- The `Toast` component has been updated with new styling and functionality.

> The following files were skipped due to too many changes: `packages/uikit/src/contexts/ToastsContext/Provider.tsx`, `pnpm-lock.yaml`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by chefjackson** [comment]
@SocketSecurity ignore semver@2.3.2

**Review by chefjackson — COMMENTED** [review]
Nice! Please help resolve the lint error

**Comment by chef-jojo** [comment]
> Nice! Please help resolve the lint error

It's because the lint action doesn't check eslint ignore (probably because turbo issue with github)

**Review by chefjackson — APPROVED** [review]

**Comment by chef-jojo** [comment]
@chefjackson regarding the lint issue
here's the follow up fix
https://github.com/pancakeswap/pancake-frontend/pull/8662/files

**Pull request merged**
