### PR TITLE
fix: Max stake per user shown when pool is finished

### PR DESCRIPTION
**Pull request by memoyil**
Max stake per user still shown if pool is finished earlier than usual

### CODE REVIEW

**Comment by chefilip** [comment]
LGTM. It  should be the same with `max stake limit end` 

https://github.com/pancakeswap/pancake-frontend/pull/3223#issuecomment-1038674114

**Comment by memoyil** [comment]
> LGTM. It should be the same with `max stake limit end`
> 
> [#3223 (comment)](https://github.com/pancakeswap/pancake-frontend/pull/3223#issuecomment-1038674114)

Yes, I will fix the conflicts when one is merged

**Comment by chefilip** [comment]
Hi @memoyil  !

Could you help me resolve the conflict ? Thanks for your contribution

**Comment by memoyil** [comment]
> Hi @memoyil !
> 
> Could you help me resolve the conflict ? Thanks for your contribution

Done

**Pull request merged**
