### PR TITLE
chore: Update wagmi@2

### PR DESCRIPTION
**Pull request by chefilip**
---

## PR-Codex overview
This PR updates dependencies and imports across multiple files for consistency and compatibility.

### Detailed summary
- Updated dependencies to `viem` version `2.9.19`
- Changed imports from `wagmi` to `viem` in various files
- Refactored timer types from `NodeJS.Timer` to `number` for consistency

> The following files were skipped due to too many changes: `apps/web/src/views/Lottery/hooks/useNextEventCountdown.ts`, `apps/web/src/views/Pottery/hooks/useDepositPottery.tsx`, `apps/web/src/views/Pottery/hooks/useWithdrawPottery.tsx`, `apps/web/src/config/chains.ts`, `packages/wagmi/src/hooks/useSignMessage.ts`, `apps/web/src/views/Swap/hooks/useStableConfig.ts`, `apps/web/src/views/ProfileCreation/Mint.tsx`, `apps/web/src/components/PhishingWarningBanner/index.tsx`, `apps/web/src/hooks/limitOrders/useGelatoLimitOrdersLib.ts`, `apps/web/src/views/Farms/components/YieldBooster/components/ProxyFarmContainer.tsx`, `apps/web/src/views/Lottery/components/AllHistoryCard/index.tsx`, `apps/web/src/views/Voting/hooks/useGetVotingPower.tsx`, `apps/web/src/state/farms/index.ts`, `packages/utils/package.json`, `packages/gauges/src/contract.ts`, `apps/web/src/components/SearchModal/OnRampCurrencySearch.tsx`, `apps/web/src/views/ProfileCreation/contexts/ProfileCreationProvider.tsx`, `apps/web/src/views/Farms/components/YieldBooster/hooks/useBoostMultiplier.ts`, `apps/web/src/state/nftMarket/helpers.ts`, `apps/web/src/views/Farms/hooks/useBCakeProxyContractAddress.ts`, `packages/gauges/package.json`, `apps/web/src/views/PancakeSquad/components/Header/CtaButtons.tsx`, `apps/web/src/components/Menu/hooks/useIfoStatus.ts`, `apps/web/src/views/Swap/MMLinkPools/utils/exchange.ts`, `apps/web/src/hooks/useUns.ts`, `apps/web/src/views/Nft/market/Home/Newest.tsx`, `apps/web/src/views/LandingV4/components/Features.tsx`, `apps/web/src/state/info/constant.ts`, `apps/web/src/state/predictions/helpers.ts`, `apps/web/src/views/Farms/hooks/useFarmCProxyAddress.ts`, `packages/ifos/src/queries/getBridgeICakeGasFee.ts`, `apps/web/src/views/FarmAuction/components/ReclaimBidCard.tsx`, `packages/v3-sdk/package.json`, `scripts/package.json`, `apps/web/src/views/Farms/components/YieldBooster/hooks/bCakeV3/useUpdateLiquidity.ts`, `apps/web/src/views/Nft/market/ActivityHistory/utils/fetchActivityNftMetadata.tsx`, `apps/web/src/views/Nft/market/Collection/IndividualNFTPage/OneOfAKindNftPage/index.tsx`, `apps/web/src/components/SearchModal/OnRampCurrencyList.tsx`, `packages/ifos/package.json`, `apps/web/src/views/Nft/market/Collection/IndividualNFTPage/shared/MoreFromThisCollection.tsx`, `apps/web/src/hooks/useTokenAllowance.ts`, `apps/web/src/views/PancakeSquad/components/Buttons/BuyTickets.tsx`, `apps/web/src/hooks/useTokenFee.ts`, `apps/web/src/views/Pools/components/Modals/ZkSyncWarning.tsx`, `packages/pools/package.json`, `packages/farms/package.json`, `packages/awgmi/package.json`, `packages/wagmi/package.json`, `apps/web/src/views/ProfileCreation/ConfirmProfileCreationModal.tsx`, `apps/web/src/views/Farms/index.tsx`, `packages/wagmi/src/useWeb3React.ts`, `apps/web/src/views/Nft/market/components/BuySellModals/SellModal/index.tsx`, `apps/web/src/pages/_app.tsx`, `apps/web/src/views/Farms/hooks/v3/useFarmV3Actions.tsx`, `apps/web/src/views/Voting/helpers.ts`, `packages/smart-router/evm/fot.ts`, `apps/web/src/views/AddLiquidityV3/IncreaseLiquidityV3.tsx`, `apps/web/src/views/Farms/components/FarmCard/HarvestAction.tsx`, `apps/web/src/views/Swap/MMLinkPools/hooks/useMMConfirmModalState.ts`, `apps/web/src/views/Ifos/components/IfoFoldableCard/IfoPoolCard/VestingClaimButton.tsx`, `apps/web/src/views/CakeStaking/hooks/useVeCakeTotalSupply.ts`, `apps/web/src/hooks/useMerkl.tsx`, `apps/web/vitest.config.ts`, `apps/web/src/views/Pottery/components/Pot/Claim/WithdrawButton.tsx`, `apps/web/src/config/__tests__/tokens.test.ts`, `apps/web/src/views/LiquidStaking/components/WithdrawRequest/index.tsx`, `apps/web/src/state/lottery/getUserTicketsData.ts`, `apps/web/src/hooks/useAccountActiveChain.ts`, `packages/uikit/package.json`, `apps/web/src/state/pools/index.ts`, `apps/web/src/views/PancakeSquad/components/Buttons/Mint.tsx`, `apps/web/src/views/Pottery/hooks/useApprovePottery.tsx`, `apps/web/src/views/Migration/components/bCake/V2StakedButton.tsx`, `packages/pcsx-sdk/src/utils/NonceManager.ts`, `apps/web/src/views/Farms/components/FarmTable/Actions/HarvestAction.tsx`, `.changeset/chilled-shoes-warn.md`, `apps/web/src/views/Pottery/components/Pot/Deposit/DepositButton.tsx`, `apps/web/src/config/constants/types.ts`, `apps/web/src/hooks/usePermit2.ts`, `apps/web/src/utils/index.ts`, `packages/pcsx-sdk/src/utils/OrderQuoter.ts`, `apps/web/src/views/FixedStaking/hooks/useHandleWithdrawSubmission.tsx`, `apps/web/src/state/farmsV3/hooks.ts`, `packages/smart-router/package.json`, `apps/web/src/components/NetworkModal/WrongNetworkModal.tsx`, `apps/web/src/views/Lottery/components/ClaimPrizesModal/ClaimPrizesInner.tsx`, `apps/web/src/hooks/useETHApprovalStatus.ts`, `apps/web/src/views/PositionManagers/hooks/useAdapterInfo.ts`, `apps/web/src/views/AddLiquidityV3/formViews/V3FormView/index.tsx`, `apps/web/src/views/Home/hooks/useCakeEmissionPerBlock.tsx`, `apps/web/src/testUtils.tsx`, `apps/web/src/views/Farms/components/YieldBooster/hooks/bCakeV3/useBoostBcakeV3.ts`, `apps/web/src/views/GaugesVoting/hooks/useUserVote.ts`, `apps/web/src/components/Menu/UserMenu/WalletInfo.tsx`, `apps/web/src/views/LiquidStaking/hooks/useLiquidStakingApprovalStatus.tsx`, `packages/gauges/src/fetchAllKilledGauges.ts`, `apps/web/src/views/Nft/market/hooks/useCompleteNft.tsx`, `apps/web/src/views/Farms/hooks/useApproveFarm.ts`, `apps/web/src/hooks/usePublicNodeWaitForTransaction.ts`, `apps/web/src/hooks/useAccountLocalEventListener.ts`, `apps/web/src/state/pottery/fetchUserPottery.ts`, `packages/gauges/src/fetchAllGauges.ts`, `apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalStateV2.ts`, `apps/web/src/views/LiquidStaking/hooks/useReadWithdrawRequestInfo.ts`, `apps/web/src/state/farms/fetchMasterChefData.ts`, `apps/web/src/state/lottery/helpers.ts`, `apps/web/src/views/Pools/components/RevenueSharing/BenefitsModal/index.tsx`, `apps/aptos/views/Ifos/components/IfoVesting/VestingPeriod/Claim.tsx`, `apps/web/src/views/Farms/components/YieldBooster/hooks/bCakeV3/useBCakeV3Info.ts`, `packages/multicall/src/getMulticallContract.ts`, `apps/web/src/views/Farms/hooks/useFetchOraclePrice.ts`, `apps/web/src/hooks/useGetENSAddressByName.ts`, `apps/web/src/views/Farms/components/YieldBooster/hooks/useProxyCAKEBalance.ts`, `apps/web/src/views/Farms/components/FarmCard/StakeAction.tsx`, `apps/web/src/hooks/useStableSwapInfo.ts`, `apps/web/src/views/RemoveLiquidity/RemoveStableLiquidity/hooks/useStableDerivedBurnInfo.ts`, `apps/web/src/views/ProfileCreation/ProfilePicture.tsx`, `packages/ifos/src/queries/fetchUserIfo.ts`, `apps/web/src/views/Ifos/components/IfoSteps.tsx`, `apps/web/src/state/pottery/fetchPottery.ts`, `apps/blog/package.json`, `apps/web/src/views/AddLiquidityV3/components/ApproveLiquidityTokens.tsx`, `apps/web/src/hooks/useContract.ts`, `packages/ifos/src/utils/getInfoSenderContract.ts`, `apps/web/src/components/ConnectWalletButton.tsx`, `apps/web/src/hooks/useDomain.ts`, `apps/web/src/utils/viem.ts`, `apps/web/src/components/App/Transactions/TransactionsModal.tsx`, `apps/web/src/views/Predictions/components/CollectWinningsPopup.tsx`, `apps/web/src/state/user/hooks/index.tsx`, `apps/web/src/state/wallet/hooks.ts`, `packages/pools/src/queries/fetchPools.ts`, `apps/web/src/state/nftMarket/hooks.ts`, `apps/web/src/utils/achievements.ts`, `apps/web/src/views/Pools/components/RevenueSharing/JoinRevenueModal/VCakeModal.tsx`, `apps/web/src/views/Pools/components/LockedPool/Modals/ExtendDurationModal.tsx`, `apps/web/src/hooks/useCakeApprovalStatus.ts`, `apps/web/src/views/CakeStaking/hooks/useVeCakeUserCreditWithTime.ts`, `apps/web/src/hooks/useApproveConfirmTransaction.tsx`, `apps/web/src/views/AddLiquidityV3/components/V3SubmitButton.tsx`, `packages/widgets-internal/package.json`, `apps/web/src/components/NetworkSwitcher.tsx`, `apps/web/src/views/AddLiquidity/index.tsx`, `apps/web/src/Providers.tsx`, `apps/web/package.json`, `apps/web/src/state/farms/fetchPublicFarmData.ts`, `apps/web/src/views/Ifos/components/IfoVesting/VestingPeriod/Claim.tsx`, `apps/web/src/views/Farms/components/YieldBooster/hooks/useYieldBoosterState.ts`, `apps/web/src/views/CakeStaking/hooks/useProxyVeCakeBalance.ts`, `apps/web/src/views/CakeStaking/hooks/useProxyVeCakeBalanceOfAtTime.ts`, `apps/web/src/hooks/useActiveChainId.ts`, `apps/web/src/components/AddToWallet/AddToWalletButton.tsx`, `packages/pools/src/utils/getPoolContractBySousId.ts`, `apps/web/src/views/Swap/MMLinkPools/hooks/useApprove.ts`, `apps/games/package.json`, `apps/web/src/hooks/useEagerConnect.ts`, `apps/web/src/views/FarmAuction/helpers.tsx`, `apps/web/src/views/Predictions/hooks/usePollOraclePrice.ts`, `packages/pools/src/queries/fetchUserPoolsData.ts`, `packages/swap-sdk/src/fetcher.ts`, `apps/web/src/views/Swap/V3Swap/hooks/useConfirmModalState.ts`, `apps/web/src/views/Profile/components/EditProfileModal/ChangeProfilePicView.tsx`, `apps/web/src/views/LiquidStaking/hooks/useCallStakingContract.tsx`, `apps/web/src/views/Home/hooks/useFarmsWithBalance.tsx`, `apps/web/src/views/Swap/MMLinkPools/components/MMCommitButton.tsx`, `apps/web/src/views/Swap/V3Swap/hooks/useSwapCallbackV2.ts`, `apps/web/src/views/CakeStaking/hooks/useAPR.ts`, `apps/web/src/views/Farms/components/YieldBooster/hooks/useProxyStakedActions.ts`, `apps/web/src/views/Nft/market/components/BuySellModals/BuyModal/ReviewStage.tsx`, `apps/web/src/pages/profile/pancake-collectibles.tsx`, `apps/web/src/views/Farms/components/UpdatePositionsReminder.tsx`, `apps/web/src/views/AddLiquidity/AddStableLiquidity/index.tsx`, `apps/web/src/hooks/useAuth.tsx`, `apps/bridge/components/WormHole/constants.ts`, `apps/web/src/views/CakeStaking/hooks/useVeCakeUserInfo.ts`, `apps/web/src/views/Predictions/components/ChainlinkChart.tsx`, `apps/web/src/views/Home/components/CakeDataRow.tsx`, `apps/web/src/utils/contractHelpers.ts`, `apps/web/src/views/Swap/MMLinkPools/hooks/useSwapCallback.ts`, `apps/web/src/views/FixedStaking/hooks/useStakedPools.ts`, `apps/web/src/hooks/useCatchTxError.tsx`, `apps/web/src/hooks/useApproveCallback.ts`, `apps/aptos/package.json`, `apps/web/src/views/Swap/V3Swap/hooks/useSendSwapTransaction.ts`, `apps/web/src/state/block/hooks.ts`, `packages/chains/tsup.config.bundled_h7syd7szdge.mjs`, `packages/smart-router/evm/v3-router/providers/poolProviders/onChainPoolProviders.ts`, `apps/web/src/hooks/useTokenBalance.ts`, `apps/web/src/utils/calls/estimateGas.ts`, `apps/web/src/views/Swap/V3Swap/hooks/useSwapCallback.ts`, `apps/web/src/hooks/v3/useV3Positions.ts`, `apps/web/src/hooks/useAccountEventListener.ts`, `apps/web/src/views/AddLiquidityV3/Migrate.tsx`, `apps/web/src/utils/calls/farms.ts`, `apps/web/src/hooks/useCallWithGasPrice.ts`, `apps/web/src/config/wallet.ts`, `apps/web/src/pages/liquidity/[tokenId].tsx`, `apps/web/src/hooks/useSwitchNetwork.ts`, `apps/web/src/views/RemoveLiquidity/RemoveLiquidityV3.tsx`, `apps/web/src/state/farms/fetchFarmUser.ts`, `apps/web/src/views/RemoveLiquidity/index.tsx`, `apps/web/src/utils/wagmi.ts`, `packages/wagmi/connectors/trustWallet/trustWallet.ts`, `apps/web/src/state/multicall/hooks.ts`, `apps/web/src/config/nodes.ts`, `packages/wagmi/connectors/blocto/blocto.ts`, `pnpm-lock.yaml`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by chef-jojo** [comment]
I think you have to upgrade wagmi and viem all together

**Comment by chefjackson** [comment]
I'll convert to draft first since it's not ready to be reviewed

**Comment by chefilip** [comment]
> @chefilip we have one workaround for wagmi/viem, can you check it is fixed too ?

Can you share the code? I will take a look.

**Comment by chefjackson** [comment]
@SocketSecurity ignore npm/@babel/plugin-proposal-async-generator-functions@7.20.7
@SocketSecurity ignore npm/@babel/plugin-proposal-numeric-separator@7.18.6
@SocketSecurity ignore npm/@babel/plugin-proposal-optional-catch-binding@7.18.6
@SocketSecurity ignore npm/@emotion/babel-plugin@11.11.0
@SocketSecurity ignore npm/@jest/create-cache-key-function@29.7.0
@SocketSecurity ignore npm/@metamask/sdk-install-modal-web@0.14.1
@SocketSecurity ignore npm/@metamask/sdk-communication-layer@0.14.3
@SocketSecurity ignore npm/@react-native/babel-preset@0.73.21
@SocketSecurity ignore npm/@react-native/metro-babel-transformer@0.73.15
@SocketSecurity ignore npm/@parcel/watcher-wasm@2.4.1
@SocketSecurity ignore npm/@react-native-community/cli@12.3.6
@SocketSecurity ignore npm/@react-native-community/cli-platform-android@12.3.6

**Comment by chefjackson** [comment]
@SocketSecurity ignore npm/@react-native-community/cli-platform-ios@12.3.6
@SocketSecurity ignore npm/@react-native-community/cli-clean@12.3.6
@SocketSecurity ignore npm/@react-native-community/cli-config@12.3.6
@SocketSecurity ignore npm/@react-native-community/cli-doctor@12.3.6
@SocketSecurity ignore npm/@react-native-community/cli-hermes@12.3.6
@SocketSecurity ignore npm/@react-native-community/cli-server-api@12.3.6
@SocketSecurity ignore npm/@react-native-community/cli-tools@12.3.6
@SocketSecurity ignore npm/@emotion/react@11.11.4
@SocketSecurity ignore npm/@emotion/styled@11.11.5
@SocketSecurity ignore npm/@emotion/serialize@1.1.4

**Comment by chef-jojo** [comment]
Remember to bump all related sdk version to major. We can hold the release until web is stable

**Review by chefjackson — APPROVED** [review]

**Review by chefjackson — APPROVED** [review]

**Pull request merged**
