### PR TITLE
style: Remove extra scrollbar in currency search modal (#2296)

### PR DESCRIPTION
**Pull request by Jds-23**
Before:
Screenshot (219)

After fix:
Screenshot (222)

### CODE REVIEW

**Comment by memoyil** [comment]
Have you tested this on mobile?

**Comment by Jds-23** [comment]
> Have you tested this on mobile? can you change your branch name to start with "feature/" so there will be a deploy preview

Yes I have.

Tested before deploying through browserstack o various mobiles.
image
image

**Comment by memoyil** [comment]
It is not working. When you disable the overflow-y, bottom part that contains manage token button cannot be seen if viewport height is small.

**Comment by Jds-23** [comment]
> cannot

will check into it

**Comment by memoyil** [comment]
You can hide the scrollbar but keep its functionality.

`/* Hide scrollbar for Chrome, Safari and Opera */
.example::-webkit-scrollbar {
  display: none;
}

/* Hide scrollbar for IE, Edge and Firefox */
.example {
  -ms-overflow-style: none;  /* IE and Edge */
  scrollbar-width: none;  /* Firefox */
} `

**Comment by Jds-23** [comment]
Yes I did that.

**Comment by Jds-23** [comment]
> You can hide the scrollbar but keep its functionality.
> 
> `/* Hide scrollbar for Chrome, Safari and Opera */
> .example::-webkit-scrollbar {
> display: none;
> }
> 
> /* Hide scrollbar for IE, Edge and Firefox _/ .example { -ms-overflow-style: none; /_ IE and Edge _/ scrollbar-width: none; /_ Firefox */
> } `

image

Getting this error continously.

**Comment by Jds-23** [comment]
I believe its good now.

**Comment by memoyil** [comment]
> I believe its good now.

Change your branch name starting with "feature/...." to make deploy preview available

**Pull request closed without merging**
