### PR TITLE
feat: Don't hide phishing warning banner when scrolling down

### PR DESCRIPTION
**Pull request by memoyil**
To reproduce: 

1. Go to website after cleaning cache
2. See phishing warning at the top
3. See it disappears (which it shouldn't) when user scrolls down

### CODE REVIEW

**Comment by chefilip** [comment]
CleanShot 2022-05-20 at 15 52 37

I think the current behavior is already visible enough for users.

**Comment by memoyil** [comment]
> CleanShot 2022-05-20 at 15 52 37 [ ](https://user-images.githubusercontent.com/97418926/169593745-0c1bb59b-2f58-4074-b54b-f3eed9c44048.gif)
> 
> I think the current behavior is already visible enough for users.

Yes but when user scrolls down it disappears without clicking close button, btw which browser you see this flickering issue

**Comment by memoyil** [comment]
@chefilip Safari transition fixed

**Comment by chef-jojo** [comment]
I don't think it's necessary to keep the banner appearing on top.

**Comment by memoyil** [comment]
> I don't think it's necessary to keep the banner appearing on top.

I will close the pr then

**Pull request closed without merging**
