### PR TITLE
fix: (lottery): Skeleton shown when round number is empty in history

### PR DESCRIPTION
**Pull request by memoyil**
To reproduce: 

1. Go to lottery 
2. Go to history
3. Remove round number to make it empty
4. See skeleton stays there

To review:

https://deploy-preview-2749--pancakeswap-dev.netlify.app/

### CODE REVIEW

**Comment by chef-jojo** [comment]
LGTM, let's fix lint warning

**Comment by memoyil** [comment]
> LGTM, let's fix lint warning

Done

**Review by chef-jojo — APPROVED** [review]

**Comment by Chef-Cheems** [comment]
@memoyil looks good. Now there is conflict, please fix 👍

**Comment by memoyil** [comment]
> @memoyil looks good. Now there is conflict, please fix 👍

Done

**Pull request merged**
