### PR TITLE
chore: cleanup config file & lint & ts check

### PR DESCRIPTION
**Pull request by ChefJerry**
### Summary
🐛🧪📦

This pull request updates the `universal-router-sdk` package to use the latest dependencies, fix type errors, and improve the build and testing processes. It also modifies the `pnpm-lock.yaml` file to reflect the dependency changes and remove unused or outdated packages.

> _We're fixing up the code, me hearties, yo ho ho_
> _We're patching up the syntax and the imports, yo ho ho_
> _We're updating the configs and the deps, me hearties, yo ho ho_
> _We're heaving on the `tsup` on the count of three, yo ho ho_

### Walkthrough
*  Remove unused or outdated devDependencies from `packages/universal-router-sdk/package.json` and update the remaining ones to the latest versions ([link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-f6540822464dc0df575ca5e40418c32c63bce949b2fdb8fced51c4be7d3995f7L47-R53))
*  Remove dependency on @uniswap/universal-router from `packages/universal-router-sdk/package.json` and `pnpm-lock.yaml`, as it is no longer needed after using viem instead ([link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-f6540822464dc0df575ca5e40418c32c63bce949b2fdb8fced51c4be7d3995f7L70), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL1812-R1814), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL11468-L11476))
*  Fix type errors and improve type safety in `packages/universal-router-sdk/src/utils/inputTokens.ts` by importing Address from viem and casting arguments to Address and BigInt types ([link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-adc6a23eb2d9020d52c36d92f7e6494387ffc6c4bb9795bf835ec050b763ef87R2), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-adc6a23eb2d9020d52c36d92f7e6494387ffc6c4bb9795bf835ec050b763ef87L56-R58), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-adc6a23eb2d9020d52c36d92f7e6494387ffc6c4bb9795bf835ec050b763ef87L68-R71))
*  Enable TypeScript type checking and documentation for the universal-router-sdk package by uncommenting the onSuccess callback in `packages/universal-router-sdk/tsup.config.ts` ([link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-1fb01942260f31c44a66df62d70ce7409f1f6e7f3122690868d898f5f61d34c9L13-R22))
*  Improve the consistency and maintainability of the TypeScript configuration in `packages/universal-router-sdk/tsconfig.json` by using the base configuration from @pancakeswap/tsconfig and simplifying the compiler options ([link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-cee8ddc51943231b1182c280d7c9a45242afa86ae46acdbcf846c3c7e980b5cdL3-R13))
*  Fix syntax error in `packages/universal-router-sdk/test/fixtures/constants/chains.ts` by removing the invalid satisfies keyword ([link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-5acb3e938e2e409648d2d515cc65e64f858155d535fa40d0db7e4677e1f932a3L37-R37))
*  Enable testing functionality for the trade module in `packages/universal-router-sdk/test/trade.test.ts` by importing the vitest testing framework ([link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-97f69569125e6d51bbd9cb2374077f694d1f48672578ba870b20398c8cc1501eR15))
*  Update various dependencies in `pnpm-lock.yaml` to use the latest and compatible versions of subdependencies, such as supports-color, debug, postcss, typescript, and @swc/core, and remove unnecessary subdependencies, such as ts-node, typedoc, and lunr ([link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL1843-L1848), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL1863-R1845), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL6019-R5995), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL6485-R6461), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL11674-R11617), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL11695-R11638), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL11716-R11659), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL22364-R22247), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL22377-R22264), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL22395-R22277), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL25558-R25403), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL25570-L25605), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL25822-R25634), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL26408-R26164), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL26795-R26551), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL26882-L26889))
*  Remove unused dependencies from `pnpm-lock.yaml`, such as @openzeppelin/contracts, @tsconfig/node10, @tsconfig/node12, @tsconfig/node14, @tsconfig/node16, @types/chai, @types/jest, @types/mocha, chai, dotenv, arg, create-require, diff, shiki, and yn ([link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL1823-R1824), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL1855-L1857), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL8023-L8026), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL10328-L10343), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL10891-L10894), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL13019-L13032), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL13331-L13334), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL14928-L14931), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL15528-L15539), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL15763-L15767), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL17695-L17705), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL20769-L20772), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL20852-L20857), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL24104-L24111), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL26270-L26293), [link](https://github.com/pancakeswap/pancake-frontend/pull/8080/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL27643-L27647))

### CODE REVIEW

**Review by chefjackson — CHANGES_REQUESTED** [review]
kindly resolve the conflicts

**Comment by ChefJerry** [comment]
@chefjackson  pls review again

**Review by chefjackson — CHANGES_REQUESTED** [review]
lint check failed. Kindly check

**Comment by ChefJerry** [comment]
@chefjackson done

**Review by chefjackson — APPROVED** [review]

**Pull request merged**
