### PR TITLE
feat(page-section): PageSection component

### PR DESCRIPTION
**Pull request by ChefHutch**
Replace `<Section>` component with new `PageSection`, to be used across new Lottery & home pages
- Move `Section` out of trading competition, rename `PageSection`
- Range of small refactoring improvements - proptypes and naming.

### CODE REVIEW

**Review by hachiojidev — APPROVED** [review]

**Comment by hachiojidev** [comment]
Oops, didn't mean to approve this until it is ready.

**Comment by ChefHutch** [comment]
> Oops, didn't mean to approve this until it is ready.

Aha thank you @hachiojidev. When I've got the goldGradient in the uikit this should be good to go 👍

**Comment by Chef-Cheems** [comment]
Is just me or PageSlice sounds weird? Why not keep the name Section or PageSection?

**Comment by ChefHutch** [comment]
> Is just me or PageSlice sounds weird? Why not keep the name Section or PageSection?

I thought it was more descriptive. Section works, but is super generic. Could describe anything. To me - these are slices (they are also sections) 🤷.

Screenshot 2021-05-25 at 12 24 46


Screenshot 2021-05-25 at 12 24 56

**Comment by Chef-Cheems** [comment]
Never heard anyone refer to section as slice, ideally in semantic HTML you'd actually need to use `<section>` instead of `<div>` 😄  
But whatever, let the voting decide :)

**Review by hachiojidev — APPROVED** [review]

**Pull request merged**
