### PR TITLE
refactor: Migrate lotteryUtils from js to ts

### LINKED ISSUE #439: Migrate lotteryUtils to typescript
Migrate https://github.com/pancakeswap/pancake-frontend/blob/develop/src/utils/lotteryUtils.js from JS to TS

### PR DESCRIPTION
**Pull request by Armakuji**
Fix #439

### CODE REVIEW

**Comment by RabbitDoge** [comment]
@Armakuji what is the status of this pr ?

**Comment by Armakuji** [comment]
Done ✨

**Comment by RabbitDoge** [comment]
Please fix the merge conflict before we review

**Comment by Armakuji** [comment]
Ok. roger that

**Comment by RabbitDoge** [comment]
@Armakuji plz fix the conflict , and ping me when it's done so I can merge it right after in order to avoid more conflicts

**Comment by Armakuji** [comment]
Done. Fixed. @RabbitDoge

**Review by RabbitDoge — APPROVED** [review]

**Pull request merged**
