### PR TITLE
fix(stableswap): Allow one coin adding in liquidity

### PR DESCRIPTION
**Pull request by chefilip**

### CODE REVIEW

**Comment by Woody810** [comment]
image
Pie chart not correct.

**Comment by chefjackson** [comment]
Need to check the confirm modal if there's only one token supplied

**Comment by chefjackson** [comment]
@chefilip Could you help check why SonarCloud Analysis failed?

**Comment by chefilip** [comment]
> @chefilip Could you help check why SonarCloud Analysis failed?

It's related to accrued duplication of the whole codebase. Need a big refactor to reduce duplication if needed

**Comment by chefjackson** [comment]
Will continue on #5602

**Pull request closed without merging**
