### PR TITLE
chore: Remove obsolete cookie set for profile avatar

### PR DESCRIPTION
**Pull request by memoyil**

### CODE REVIEW

**Review by Chef-Cheems — CHANGES_REQUESTED** [review]
Pleases remove `js-cookie` from dependencies 🙏

**Comment by memoyil** [comment]
> Pleases remove `js-cookie` from dependencies 🙏

Done

**Comment by chef-jojo** [comment]
no yarn.lock changes 🤔

**Comment by chef-jojo** [comment]
no yarn.lock changes 🤔

**Comment by memoyil** [comment]
> no yarn.lock changes 🤔

Forgot to run yarn install, Done 👍

**Review by Chef-Cheems — APPROVED** [review]

**Pull request merged**
