### PR TITLE
chore: Cakepie ifo

### PR DESCRIPTION
**Pull request by chefjackson**
---

## PR-Codex overview
This PR focuses on updating the image URLs and adding a new IFO (CAKEPIE). 

### Detailed summary
- Updated image URLs for IFO backgrounds
- Added a new IFO: CAKEPIE
- Updated the `getBannerUrl` function to include the asset CDN URL
- Added cross-origin attribute to image element in `useImageColor` hook
- Added a new token (CKP) in the tokens configuration
- Updated the `IfoSalesLogo` component to include a size prop
- Updated the translations for "Your max CAKE entry" to "Your ICAKE"
- Added a new IFO configuration for CAKEPIE
- Updated the `useGetWalletIfoData` hook to use the `useIfoCredit` hook
- Updated the `VeCakeCard` component to use the `useIsUserDelegated` hook
- Updated the `IfoFoldableCard` component to include a tooltip for max token entry
- Updated the `IfoCardDetails` component to include the sum of taxes overflow
- Updated the `IfoSteps` component to remove unused imports and functions

> The following files were skipped due to too many changes: `apps/web/src/views/Ifos/components/IfoSteps.tsx`, `apps/web/public/images/achievements/ifo-ckp.svg`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by ChefJerry** [comment]
image

token logo url is not correct

**Comment by ChefJerry** [comment]
click one enable, both loading
image

**Comment by chefjackson** [comment]
> image
> 
> token logo url is not correct

Which chain are you on?

**Comment by chefjackson** [comment]
> click one enable, both loading image

All the UE will follow the previous ifos and we're not going to update them for this ifo

**Comment by ChefJerry** [comment]
> > image
> > token logo url is not correct
> 
> Which chain are you on?

on BSC 

https://tokens.pancakeswap.finance/images/undefined0x985d5915A01b83ad5eF42AB4FD16C3fe27F6A1C6.png

**Review by ChefJerry — APPROVED** [review]

**Pull request merged**
