### PR TITLE
fix(CAKE Staking): Fix HelpIcon color & BubbleBox

### PR DESCRIPTION
**Pull request by Woody810**
### Summary
🎨🗨️🍰

Changed the help icon color in the `NewCakeStakingCard` component to improve the UI consistency. This component shows the user how to stake cake tokens and earn rewards.

> _`help` icon changes_
> _subtle color for the cake_
> _autumn of design_

### Walkthrough
* Changed the help icon color to subtle in the cake staking card button ([link](https://github.com/pancakeswap/pancake-frontend/pull/8423/files?diff=unified&w=0#diff-8b6cf6b37d7a32685b877de2de319e180e5da1caa692cbf8d9ab18b90f258e4fL36-R36)) to match the design of the speech bubble box

### CODE REVIEW

**Comment by ChefMomota** [comment]
Can u fix this in mobile?

Screenshot 2023-11-23 at 10 12 20 AM

**Comment by Woody810** [comment]
> Can u fix this in mobile?
> 
> Screenshot 2023-11-23 at 10 12 20 AM

sure, will fix it later

**Comment by ChefMomota** [comment]
In light theme a bit weird.

Screenshot 2023-11-23 at 12 10 30 PM

**Comment by Woody810** [comment]
> In light theme a bit weird.
> 
> Screenshot 2023-11-23 at 12 10 30 PM

Fixed

**Comment by chefjackson** [comment]
image

Could you help hide the underline as well?

**Comment by Woody810** [comment]
> image
> Could you help hide the underline as well?

Fixed.

**Review by ChefMomota — APPROVED** [review]

**Pull request merged**
