### PR TITLE
feat: (farm): Add missing past auction hosting ends date data

### PR DESCRIPTION
**Pull request by memoyil**
To review: 

1. Go to farms
2. See past auction hosting ends data on farm auction farms even the hosting ends

### CODE REVIEW

**Comment by chef-jojo** [comment]
I think some auction calls can utilize subgraph, not necessarily to be synced in time. 
oh wait, [the subgraph ](https://github.com/pancakeswap/pancake-subgraph/tree/v2/subgraphs/farm-auctions) never deployed? 🤔

**Comment by memoyil** [comment]
> I think some auction calls can utilize subgraph, not necessarily to be synced in time.
> oh wait, [the subgraph ](https://github.com/pancakeswap/pancake-subgraph/tree/v2/subgraphs/farm-auctions) never deployed? 🤔



> I think some auction calls can utilize subgraph, not necessarily to be synced in time.
> oh wait, [the subgraph ](https://github.com/pancakeswap/pancake-subgraph/tree/v2/subgraphs/farm-auctions) never deployed? 🤔

Afaik we never used subgraph for auctions therefore i think it is not deployed. Current implementation with onchain contract  making 2 calls per user session (fetching the current auction id and the multicall) only if user visits farms page. It is better to have subgraph to reduce the call to 1 but imho the current approach also has not much performance impact.

**Comment by memoyil** [comment]
> I think some auction calls can utilize subgraph, not necessarily to be synced in time.
> oh wait, [the subgraph ](https://github.com/pancakeswap/pancake-subgraph/tree/v2/subgraphs/farm-auctions) never deployed? 🤔



> I think some auction calls can utilize subgraph, not necessarily to be synced in time.
> oh wait, [the subgraph ](https://github.com/pancakeswap/pancake-subgraph/tree/v2/subgraphs/farm-auctions) never deployed? 🤔

Afaik we never used subgraph for auctions therefore i think it is not deployed. Current implementation with onchain contract  making 2 calls per user session (fetching the current auction id and the multicall) only if user visits farms page. It is better to have subgraph to reduce the call to 1 but imho the current approach also has not much performance impact.

**Comment by chefilip** [comment]
As discussed, this feature isn't important enough to add more loop and logic in codebase. I will close the PR.

**Pull request closed without merging**
