### PR TITLE
feat: Add Space ID integrations

### PR DESCRIPTION
**Pull request by mingyan-space**
Adds Space ID domain name resolving methods for .bnb names.

Both resolving and reversed resolving methods are provided.

### CODE REVIEW

**Comment by chefilip** [comment]
Thanks for your contribution. @mingyan-space 

Is it possible if the lib `@siddomains/sidjs` could reuse ether project dependencies from host projects instead of forcing the host project update their own ether package ?

**Comment by mingyan-space** [comment]
> Thanks for your contribution. @mingyan-space
> 
> Is it possible if the lib `@siddomains/sidjs` could reuse ether project dependencies from host projects instead of forcing the host project update their own ether packages ?

Hi @chefilip , thank you so much for your advice. We have updated our SDK to make it possible not to update ether package. Please review our PR and comment if there is further problems.

**Comment by chefilip** [comment]
Thanks for your contribution. We will review it

**Review by chefilip — APPROVED** [review]

**Comment by chefilip** [comment]
Hi @mingyan-space 

Could you help me check prettier?

**Comment by mingyan-space** [comment]
Hi @chefilip, thank you for your feedback. I just solved lint issue. Please check again.
Thank you.

**Pull request closed without merging**
