### PR TITLE
feat: update defiedge position manager fee to 10%

### PR DESCRIPTION
**Pull request by ChefBingbong**
---

## PR-Codex overview
This PR increases the fee tier from LOW to HIGH across various vault configurations in different networks.

### Detailed summary
- Updated fee tier from LOW to HIGH in vault configurations for different networks (BSC, Arbitrum, zkSync)
- Maintained consistency in strategy and manager values

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by chefjackson** [comment]
@Chef-Yogi please help double check

**Comment by Chef-Yogi** [comment]
I am guessing the fee is not the LP fee tier.
maybe it's about the manager Fee

**Comment by Chef-Yogi** [comment]
Double check with PM now

**Comment by chefjackson** [comment]
Please reopen after confirmation

**Pull request closed without merging**
