### PR TITLE
Refactoring: fetch status enums #2580

### PR DESCRIPTION
**Pull request by bariOmymen**
- [ x ] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-frontend/blob/master/CONTRIBUTING.md) first

[ x ] If your PR is work in progress, open it as `draft`
[ x ] Before requesting a review, all the checks need to pass
[ x ] Explain what your PR does
deleted duplicate Fetch status enums and made one standard Fetch status enum for all the code.
I need some feedback on the changes that I made and if I missed anything.
 I'm a first timer so I'm not so sure I covered everything.

### CODE REVIEW

**Comment by memoyil** [comment]
@bariOmymen @Chef-Cheems Imho, we should do this refactoring separately for each component that currently uses different fetch status enum. In that way we can test the functionality easier.

**Comment by bariOmymen** [comment]
> @bariOmymen @Chef-Cheems Imho, we should do this refactoring separately for each component that currently uses different fetch status enum. In that way we can test the functionality easier.

@memoyil can you elaborate on this more and explain how to do your suggestion?

**Comment by Chef-Cheems** [comment]
@memoyil I think it's fine to change everything at once. Sure it will take time to review and test but since its just enums it should be fine.

I'll take a look once I'm done with some high priority things.

**Comment by chef-jojo** [comment]
closing this in favor of  #2965

**Pull request closed without merging**
