### PR TITLE
fix: Fix 265 - Unable to view lottery tickets from past draws

### PR DESCRIPTION
**Pull request by karelianpie**
Fixes https://github.com/pancakeswap/pancake-frontend/issues/265

The issue was with this assertion `if (ticketIssue.toString() === issueIdex) {}` in `src/utils/lotteryUtils.js`. One is a string and the other a number, so when we use the triple equals for strict equality they are not equal.

I've fixed it with double equals so that it performs type coercion, I'm happy to convert the `issueIdex` to string as well if that's more preferable. I think it looks cleaner using loose equality though, but had to disable a eslint rule.

### CODE REVIEW

**Review by RabbitDoge — CHANGES_REQUESTED** [review]
Indeed, let's try to avoid disabled eslint rules as much as possible.
It's probably better to perform a conversion. Since both variables are supposed to be numbers, a conversion to number (parseInt, dont forget to add the base as second param), or BigNumber (seems overkill) makes more sense than a conversion to string.
While you are on it, can you fix the typo on `issueIdex` plz ?

This file will need to be migrated to TS at some point.

**Comment by karelianpie** [comment]
> Indeed, let's try to avoid disabled eslint rules as much as possible.
> It's probably better to perform a conversion. Since both variables are supposed to be numbers, a conversion to number (parseInt, dont forget to add the base as second param), or BigNumber (seems overkill) makes more sense than a conversion to string.

Sounds good, used `parseInt()` https://github.com/pancakeswap/pancake-frontend/pull/432/commits/ea1ede1db0b344d32498e1bcf241009f877a6c7d

> While you are on it, can you fix the typo on `issueIdex` plz ?

No worries, fixed with https://github.com/pancakeswap/pancake-frontend/pull/432/commits/5d8a47ef2f87613b39787f79357af1a207edbea2

> This file will need to be migrated to TS at some point.

I could work on that if you think it's important, let me know

**Review by hachiojidev — APPROVED** [review]
Nice job. Next time please prepend your branch name with `feature/` so a preview build is made and we can verify the fix.

**Review by hachiojidev — APPROVED** [review]

**Review by RabbitDoge — APPROVED** [review]

**Review by RabbitDoge — CHANGES_REQUESTED** [review]
Just some conflicts to resolve

**Comment by karelianpie** [comment]
> Just some conflicts to resolve

Merge conflicts resolved @RabbitDoge

**Review by RabbitDoge — APPROVED** [review]

**Pull request merged**
