### PR TITLE
chore: Fix docs in useCallWithGasPrice

### PR DESCRIPTION
**Pull request by memoyil**

### CODE REVIEW

**Comment by chef-jojo** [comment]
put it above the function has a nice hover hint, why not keep it this way?
CleanShot 2021-12-28 at 13 22 03@2x

**Review by Chef-Cheems — APPROVED** [review]

**Comment by memoyil** [comment]
> put it above the function has a nice hover hint, why not keep it this way? CleanShot 2021-12-28 at 13 22 03@2x

It is moved when you hover onto object, Imho it is better when you use that variable and see the docs
 
image

**Comment by Chef-Cheems** [comment]
> put it above the function has a nice hover hint, why not keep it this way? CleanShot 2021-12-28 at 13 22 03@2x

The hover hint shouldn't be for `useCallWithGasPrice`, it is for `callWithGasPrice`. Although with this change it will not show it for `callWithGasPrice` 🤔 idk... if you wanna keep the hint @chef-jojo we can close this PR 😄 or find a way to make hint appear on `callWithGasprice`

**Comment by memoyil** [comment]
> > put it above the function has a nice hover hint, why not keep it this way? CleanShot 2021-12-28 at 13 22 03@2x
> 
> The hover hint shouldn't be for `useCallWithGasPrice`, it is for `callWithGasPrice`. Although with this change it will not show it for `callWithGasPrice` 🤔 idk... if you wanna keep the hint @chef-jojo we can close this PR 😄 or find a way to make hint appear on `callWithGasprice`

It shows it on my IDE 🤔

**Comment by Chef-Cheems** [comment]
> > > put it above the function has a nice hover hint, why not keep it this way? CleanShot 2021-12-28 at 13 22 03@2x
> > 
> > 
> > The hover hint shouldn't be for `useCallWithGasPrice`, it is for `callWithGasPrice`. Although with this change it will not show it for `callWithGasPrice` 🤔 idk... if you wanna keep the hint @chef-jojo we can close this PR 😄 or find a way to make hint appear on `callWithGasprice`
> 
> It shows it on my IDE 🤔

VSCode? Do you have any plugins that might do that? For me its not showing anything 🤔

**Comment by memoyil** [comment]
@Chef-Cheems I am using webstorm

**Comment by Chef-Cheems** [comment]
Well, let's merge it as it moves docstring to proper place logically. Maybe VSCode someday will show it too 👀

**Pull request merged**
