### PR TITLE
fix: (affiliate-program): DefaultLink hook cache refetch not work and move to react-query

### PR DESCRIPTION
**Pull request by memoyil**
### Summary
🔄🚀🛠️

The pull request refactors the data fetching logic for various components and hooks in the `AffiliatesProgram` view, using the `useQuery` hook from `@tanstack/react-query` instead of the `useSWR` hook. This improves the performance, consistency, and error handling of the data fetching and caching across the app. The pull request also imports some utility functions from external libraries to simplify the code.

> _To fetch data with more speed and grace_
> _We replaced `useSWR` with `useQuery`_
> _From `react-query` we took_
> _Some hooks and options to cook_
> _A better caching and error handling base_

### Walkthrough
*  Replace `useSWR` hook with `useQuery` hook for data fetching and caching in various hooks ([link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-ea466405378cb17c3e020769042ee68ad5f5f276852383f92e0c709956b789b7L14-R18), [link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-4bcef3f8e01bcdc502a427e1b19ade7229e38f42066e52a8b3e76ece6c836e39L80-R105), [link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-3fc1def9923120efdb4072d887f42f09f36649508b285e1b897d9543f25e3eccL12-R16), [link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-ba8f2b8604de2c2503e1be6f65ae6a7dc9b953923fd7d16db3be7a05d287e90cL12-R16), [link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-40a6d3e2fc2ef9520f5600bb29da2dfafa581ec4a241bd977560aa8bbb549f31L32-R35), [link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-662fbc716d907bc4cf509afe6f1ae5913230be5e21242a6e7bf224e1ab64d825L12-R14), [link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-70e8e399d97015e40102cdd4792f44dbe497f0b8032c58a230fa24b665e7228eL15-R33))
*  Import `useQuery` hook from `@tanstack/react-query` and `nanoid` function from `@reduxjs/toolkit` in various hooks ([link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-ea466405378cb17c3e020769042ee68ad5f5f276852383f92e0c709956b789b7R8-R9), [link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-4bcef3f8e01bcdc502a427e1b19ade7229e38f42066e52a8b3e76ece6c836e39R5-R7), [link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-3fc1def9923120efdb4072d887f42f09f36649508b285e1b897d9543f25e3eccR4-R5), [link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-ba8f2b8604de2c2503e1be6f65ae6a7dc9b953923fd7d16db3be7a05d287e90cL2-R2), [link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-40a6d3e2fc2ef9520f5600bb29da2dfafa581ec4a241bd977560aa8bbb549f31R6), [link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-70e8e399d97015e40102cdd4792f44dbe497f0b8032c58a230fa24b665e7228eR4))
*  Import `useQueryClient` hook from `@tanstack/react-query` in `useDefaultLinkId` hook to access query client instance ([link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-ba8f2b8604de2c2503e1be6f65ae6a7dc9b953923fd7d16db3be7a05d287e90cL2-R2))
*  Add `enabled` option to `useQuery` hook to conditionally enable or disable queries based on variables in various hooks ([link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-ea466405378cb17c3e020769042ee68ad5f5f276852383f92e0c709956b789b7L38-R46), [link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-3fc1def9923120efdb4072d887f42f09f36649508b285e1b897d9543f25e3eccL25-R31), [link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-ba8f2b8604de2c2503e1be6f65ae6a7dc9b953923fd7d16db3be7a05d287e90cL31-R41), [link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-40a6d3e2fc2ef9520f5600bb29da2dfafa581ec4a241bd977560aa8bbb549f31L53-R62), [link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-662fbc716d907bc4cf509afe6f1ae5913230be5e21242a6e7bf224e1ab64d825L25-R29))
*  Rename `mutate` function to `refetch` in various hooks to use consistent naming of `useQuery` hook method for manual refetching ([link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-ea466405378cb17c3e020769042ee68ad5f5f276852383f92e0c709956b789b7L38-R46), [link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-4bcef3f8e01bcdc502a427e1b19ade7229e38f42066e52a8b3e76ece6c836e39L104-R111), [link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-40a6d3e2fc2ef9520f5600bb29da2dfafa581ec4a241bd977560aa8bbb549f31L53-R62))
*  Replace `revalidateOnFocus`, `revalidateIfStale`, `revalidateOnReconnect`, and `revalidateOnMount` options with `refetchOnFocus`, `refetchOnReconnect`, and `refetchOnMount` options in various hooks to use consistent naming and behavior of `useQuery` hook options for automatic refetching ([link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-3fc1def9923120efdb4072d887f42f09f36649508b285e1b897d9543f25e3eccL25-R31), [link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-ba8f2b8604de2c2503e1be6f65ae6a7dc9b953923fd7d16db3be7a05d287e90cL31-R41), [link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-662fbc716d907bc4cf509afe6f1ae5913230be5e21242a6e7bf224e1ab64d825L25-R29))
*  Replace `mutate` function with `queryClient.invalidateQueries` method in `useDefaultLinkId` hook to invalidate and refetch query when `randomNanoId` variable changes ([link](https://github.com/pancakeswap/pancake-frontend/pull/8183/files?diff=unified&w=0#diff-ba8f2b8604de2c2503e1be6f65ae6a7dc9b953923fd7d16db3be7a05d287e90cL23-R25))

### CODE REVIEW

**Comment by ChefMomota** [comment]
Can u check it I can't create it. In prod it work.
Screenshot 2023-10-23 at 10 56 06 AM

**Comment by ChefMomota** [comment]
> > Can u check it I can't create it. In prod it work.
> > Screenshot 2023-10-23 at 10 56 06 AM
> 
> It doesnt happen always, it happens when only the generated id is already used and a new id needed to be generated.

Yes, But just now I try after show error, click again also show it.

**Comment by chefjackson** [comment]
@memoyil @ChefMomota can we fix the problem on top of this branch?

**Comment by ChefMomota** [comment]
> @memoyil @ChefMomota can we fix the problem on top of this branch?

I will take a look before end of today

**Comment by chefjackson** [comment]
> No, this is another issue and it gets fixed by itself when there is an error. The fix that I did happens very rarely since the conflict/generating same ids not happens frequently but when it happens it cannot request another one.

Failed to request if conflict happens? This is the problem I was referring to

**Comment by ChefMomota** [comment]
> > No, this is another issue and it gets fixed by itself when there is an error. The fix that I did happens very rarely since the conflict/generating same ids not happens frequently but when it happens it cannot request another one.
> 
> Failed to request if conflict happens? This is the problem I was referring to

Let me ask BE, I think got an API is broken.

**Review by ChefMomota — APPROVED** [review]

**Pull request merged**
