### PR TITLE
chore: ifo banner mobile fontsize

### PR DESCRIPTION
**Pull request by Chef-Yogi**

### CODE REVIEW

**Comment by ChefMomota** [comment]
https://user-images.githubusercontent.com/98292246/182321322-dc617829-ca61-4fe5-9823-5e260a507694.mov

**Comment by Chef-Yogi** [comment]
Let me check, thanks

**Comment by Chef-Yogi** [comment]
@ChefMomota fixed

**Comment by ChefMomota** [comment]
Screenshot 2022-08-03 at 10 17 23 AM

Token is on top of text.

**Review by ChefMomota — APPROVED** [review]

**Pull request merged**
