### PR TITLE
chore(Swap): Change default price display

### PR DESCRIPTION
**Pull request by Woody810**
When swap from A to B, the default price display should also be A→B.

Before:
image

After:
image

### CODE REVIEW

**Comment by chefilip** [comment]
Even though your change is easy to understand, it's duplicated with the information of input -> ouput. Also, It's not aligned with the definition of price.

**Review by roymoses07 — DISMISSED** [review]
Done

**Comment by chef-jojo** [comment]
@Woody810 can you revert the order B -> A?

**Comment by Woody810** [comment]
> @Woody810 can you revert the order B -> A?

Done

**Review by chef-jojo — APPROVED** [review]

**Pull request merged**
