### PR TITLE
feat: internal widget

### PR DESCRIPTION
**Pull request by chef-jojo**
### Summary
🌾🚀🎨

This pull request refactors the farm-related UI components across the `apps/aptos` and `apps/web` packages to use the new `FarmWidget` component from the `@pancakeswap/widgets-internal` package. This improves the performance, usability, and consistency of the farm features on the website and the web app. The pull request also updates the dependencies and imports to use the `@pancakeswap/widgets-internal` package.

> _Sing, O Muse, of the valiant `pancakeswap` team, who refactored their code_
> _With skill and wisdom, they replaced the old `Farm` component with the new `FarmWidget`_
> _From the `widgets-internal` package, a gift from the gods, they drew their power_
> _And made their farm cards and tables shine like the sun, swift and splendid_

### Walkthrough
*  Replace the `Farm` component from the `@pancakeswap/uikit` package with the `FarmWidget` component from the `@pancakeswap/widgets-internal` package in various files to separate the UI components from the farm-specific logic and data ([link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-729ef9c0c01c97443585c784bdf788c8568006427edcfaf441ecfd7b499c3a48L2-R3),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-729ef9c0c01c97443585c784bdf788c8568006427edcfaf441ecfd7b499c3a48L109-R110),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-729ef9c0c01c97443585c784bdf788c8568006427edcfaf441ecfd7b499c3a48L120-R121),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-bcd987a55beb759352c064ec566201489281f100fa7e6583933bce5339554759L2-R7),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-bcd987a55beb759352c064ec566201489281f100fa7e6583933bce5339554759L39-R40),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-8b765322f2ea8353d33299240988ee1b012663574645d61810dbc0af633ff97fL5-R6),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-8b765322f2ea8353d33299240988ee1b012663574645d61810dbc0af633ff97fL13-R14),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-1bcc706e1f73c1fdf441e5e53831aee7a9922a8bf14f7683eac2ba2cc933639eL2-R3),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-1bcc706e1f73c1fdf441e5e53831aee7a9922a8bf14f7683eac2ba2cc933639eL81-R82),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-1bcc706e1f73c1fdf441e5e53831aee7a9922a8bf14f7683eac2ba2cc933639eL101-R102),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-1bcc706e1f73c1fdf441e5e53831aee7a9922a8bf14f7683eac2ba2cc933639eL136-R137),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-cedd50245481321c9908a963877cf4e2dff2d843509a02d1f1f6426c2db5d15bL2-R3),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-cedd50245481321c9908a963877cf4e2dff2d843509a02d1f1f6426c2db5d15bL19-R17),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-9d19f74657e41faa3cf4e494efa7f8060ef9d20322e862fbe6c055a8b6bb8c60L3-R4),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-9d19f74657e41faa3cf4e494efa7f8060ef9d20322e862fbe6c055a8b6bb8c60L14-R15),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-8ece6f9c8f98fc8fa92107e8e8c114bc6091d8743103cd910e1d8cfb74273b64L5-R6),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-8ece6f9c8f98fc8fa92107e8e8c114bc6091d8743103cd910e1d8cfb74273b64L129-R130),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-8ece6f9c8f98fc8fa92107e8e8c114bc6091d8743103cd910e1d8cfb74273b64L149-R150),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-8ece6f9c8f98fc8fa92107e8e8c114bc6091d8743103cd910e1d8cfb74273b64L160-R173),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-8ece6f9c8f98fc8fa92107e8e8c114bc6091d8743103cd910e1d8cfb74273b64L178-R179),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-8ece6f9c8f98fc8fa92107e8e8c114bc6091d8743103cd910e1d8cfb74273b64L188-R194),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-76f731fd4ec4551a306244484868567f4c4f754119793d02d805e25b595dcc86L1-R1),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-76f731fd4ec4551a306244484868567f4c4f754119793d02d805e25b595dcc86L7-R9),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-9ee711fe5bdd70f4933930da0842f6ac5a59fa752d84fdf15e1ad8ae2a546d3bL3-R4),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-9ee711fe5bdd70f4933930da0842f6ac5a59fa752d84fdf15e1ad8ae2a546d3bL25-R23),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-e0a5accbd3cd0970d5c03017ff1c08690c2847c1bd01aec6294836c61b9cfe0dL20-R22),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-e0a5accbd3cd0970d5c03017ff1c08690c2847c1bd01aec6294836c61b9cfe0dL306-R306),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-507fb0239284fe97099cb1a15cbeafa55cc779a34aff1fa311d0dd39ee3c95f8L4-R5),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-507fb0239284fe97099cb1a15cbeafa55cc779a34aff1fa311d0dd39ee3c95f8L10-R11),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-2e0a28c02ce581e54b6b6f5803ee5d4b292c79f235eeeaed29cfc4666fa7cad0R29),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-14b60f636e1a2b0061da57aaf231cb1ed15a5dc0c592425ed82e58fec95d42d8R52),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-99cc199074209bdf8fe96c89eb7c76ae1e7f5858c67da50acb14f5a8361ba52dL9),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-99cc199074209bdf8fe96c89eb7c76ae1e7f5858c67da50acb14f5a8361ba52dR24),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-99cc199074209bdf8fe96c89eb7c76ae1e7f5858c67da50acb14f5a8361ba52dL423-R423),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-7c64c760be1e393dee45fb35e38cd0932308e931c85928c64cd5d66186d8440fL16),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-7c64c760be1e393dee45fb35e38cd0932308e931c85928c64cd5d66186d8440fR31),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-7c64c760be1e393dee45fb35e38cd0932308e931c85928c64cd5d66186d8440fL500-R500),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-02d07d878611b08c65ffbda68d21d02a392e25c9c83640035a308ea064d802d6L3-R4),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-02d07d878611b08c65ffbda68d21d02a392e25c9c83640035a308ea064d802d6L155-R156),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-02d07d878611b08c65ffbda68d21d02a392e25c9c83640035a308ea064d802d6L171-R172),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-6f6483f176b9edb2af9f59ce5d5143a0ac1cdf6c7c2659a15a48bec0dc40bc0bL2-R8),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-6f6483f176b9edb2af9f59ce5d5143a0ac1cdf6c7c2659a15a48bec0dc40bc0bL48-R49),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-17570c6d0362ef1eaa02e9e7d138355491e242bc65b594ffd1eda8b620294565L3-R4),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-17570c6d0362ef1eaa02e9e7d138355491e242bc65b594ffd1eda8b620294565L21-R22),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-186fbd94878c47f423902f8d07b53e23174a8bc05de62a1a30ae09aa94a91142L2-R3),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-186fbd94878c47f423902f8d07b53e23174a8bc05de62a1a30ae09aa94a91142L56-R49),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-d76b6acfb1ab5622312026783916faf38d569dd3ce98bc30157bc66cb8ae1e7fL2-R3),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-d76b6acfb1ab5622312026783916faf38d569dd3ce98bc30157bc66cb8ae1e7fL240-R241),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-d76b6acfb1ab5622312026783916faf38d569dd3ce98bc30157bc66cb8ae1e7fL271-R272),[link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-d76b6acfb1ab5622312026783916faf38d569dd3ce98bc30157bc66cb8ae1e7fL323-R324))
*  Use the `FARMS_SMALL_AMOUNT_THRESHOLD` constant from the `FarmWidget` package instead of the `@pancakeswap/uikit` package in the `apps/web/src/views/Farms/components/FarmCard/HarvestAction.tsx` file as it is related to the farm-specific logic and data ([link](https://github.com/pancakeswap/pancake-frontend/pull/7770/files?diff=unified&w=0#diff-186fbd94878c47f423902f8d07b53e23174a8bc05de62a1a30ae09aa94a91142L56-R49))

### CODE REVIEW

**Comment by chef-jojo** [comment]
@SocketSecurity ignore conventional-recommended-bump@8.0.0

**Review by chefjackson — COMMENTED** [review]
Shall we add `@pancakeswap/widgets-internal` to `transpilePackages` here? https://github.com/pancakeswap/pancake-frontend/blob/develop/apps/web/next.config.mjs#L54

Also we can remove published pkgs like pools

**Comment by chef-jojo** [comment]
> Shall we add `@pancakeswap/widgets-internal` to `transpilePackages` here? https://github.com/pancakeswap/pancake-frontend/blob/develop/apps/web/next.config.mjs#L54
> 
> 
> 
> Also we can remove published pkgs like pools

transpilePackages is helping to transform es6 to es5
Don't think it's needed, since we use tsconfig to treat it as source code directly

**Comment by chefjackson** [comment]
> > Shall we add `@pancakeswap/widgets-internal` to `transpilePackages` here? https://github.com/pancakeswap/pancake-frontend/blob/develop/apps/web/next.config.mjs#L54
> > Also we can remove published pkgs like pools
> 
> transpilePackages is helping to transform es6 to es5 Don't think it's needed, since we use tsconfig to treat it as source code directly

You mean here? https://github.com/pancakeswap/pancake-frontend/blob/develop/packages/tsconfig/nextjs.json#L17

We only specify the path to uikit but not internal widget

**Comment by chef-jojo** [comment]
> > > Shall we add `@pancakeswap/widgets-internal` to `transpilePackages` here? https://github.com/pancakeswap/pancake-frontend/blob/develop/apps/web/next.config.mjs#L54
> > > Also we can remove published pkgs like pools
> > 
> > 
> > transpilePackages is helping to transform es6 to es5 Don't think it's needed, since we use tsconfig to treat it as source code directly
> 
> You mean here? https://github.com/pancakeswap/pancake-frontend/blob/develop/packages/tsconfig/nextjs.json#L17
> 
> We only specify the path to uikit but not internal widget

umm right my bad, it's just using main field on package.json. no harm to add that, updated

**Review by chefjackson — APPROVED** [review]

**Pull request merged**
