### PR TITLE
feat(farms-pagination): Add pagination to farm table

### PR DESCRIPTION
**Pull request by noblica**
Hey, I saw that [this issue](https://github.com/pancakeswap/pancake-frontend/issues/422) was quite old, so I tried solving it.

Added pagination to the table view of Farms, since loading this many items in the DOM slows it down quite a lot.
First PR on here, I tried to follow all the laid out guidelines, but if you feel that I missed something, or that something should be done differently, please let me know so I can change it.

Here's the preview for large screens:
farms-large

And here's the preview for small screens:
farms-small

I purposely removed the "ROWS PER PAGE" selection for smaller screens, but it can be re-added easily. Also I only touched the table view, didn't touch the card view. Maybe something like infinite loading could be done there, if needed.

This PR closes: https://github.com/pancakeswap/pancake-frontend/issues/422

### CODE REVIEW

**Comment by Chef-Chungus** [comment]
Thanks for your submission. We will need to run this by our UX/UI designer, however, at a first glance it seems this would inhibit the usability of the page.

Will let you know once I have some feedback

**Comment by noblica** [comment]
@Chef-Chungus Hey, thanks for the reply.
Also, no worries, I'm not much of a designer anyway. Just saw the issue, and thought I'd take a stab at it.

**Comment by Chef-Chungus** [comment]
Thanks for the initiative, we appreciate it. 
I'll take a look to see if we have something designer-approved if you're interested in trying on another task

Will let you know tomorrow

**Comment by noblica** [comment]
@Chef-Chungus sounds good, please let me know if something is available 🙂

**Comment by memoyil** [comment]
Lazy loading is a better option and better fit to mobile experience like android recyclerview imho..

**Comment by noblica** [comment]
It could be implemented with Intersection Observers. It also could be a unified solution for both the table, and the card view.

**Comment by memoyil** [comment]
We can close this pr and focus on the new one #909

**Comment by noblica** [comment]
Closing in favor of https://github.com/pancakeswap/pancake-frontend/pull/909

**Pull request closed without merging**
