### PR TITLE
chore: improve chinese translation

### PR DESCRIPTION
**Pull request by woodywu810**

### CODE REVIEW

**Comment by woodywu810** [comment]
Hey @chef-jojo, can you please help review this PR? Thank you!

**Comment by chef-jojo** [comment]
> Hello @chef-jojo, can you please help review this PR? Thank you!

Thanks for the PR. Looks good to me!
We have to sync it back to Crowdin since it's automatically pulling from them.

**Comment by woodywu810** [comment]
> > Hello @chef-jojo, can you please help review this PR? Thank you!
> 
> Thanks for the PR. Looks good to me! We have to sync it back to Crowdin since it's automatically pulling from them.

Understand, if syncing back to crowdin is done, please close this PR, thanks.

**Comment by woodywu810** [comment]
> > Hello @chef-jojo, can you please help review this PR? Thank you!
> 
> Thanks for the PR. Looks good to me! We have to sync it back to Crowdin since it's automatically pulling from them.

Understand, if syncing back to crowdin is done, please close this PR, thanks.

**Review by chef-jojo — APPROVED** [review]

**Pull request merged**
